# Dependabot configuration for risk-engine-js
# Epic: TSE-0002 - Security Hardening and Audit Framework
# Date: {{DATE}}
#
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm dependencies - daily checks
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"

    # Group minor/patch updates to reduce PR noise
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

    # Ignore specific packages if needed (document rationale)
    # ignore:
    #   - dependency-name: "react"
    #     versions: [">=19.0.0"]
    #     # Rationale: React 19 introduces breaking changes, planned upgrade in Q2

  # GitHub Actions - weekly checks
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
      - "automated"
