name: Backdoor Reconnaissance

on:
  push:
    branches: [ main, "security/**", "deploy/**" ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 4'  # Weekly Thursday
  workflow_dispatch:

# Prevent redundant scans on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  recon:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obfuscation markers
        run: |
          echo "=== Obfuscation Markers ==="
          rg -n "while\\(!!\\[\\]\\)|\\bFunction\\(|\\beval\\(|atob\\(|Buffer\\.from.*base64" --type js --type ts || echo "None found"
        continue-on-error: true

      - name: Hidden networking
        run: |
          echo "=== Hidden Networking ==="
          rg -n 'require\\(.(http|https|net|dgram).\\)|new\\s+WebSocket\\(' --type js --type ts || echo "None found"
        continue-on-error: true
